/****** Object:  Database [CollegeStudents]    Script Date: 6/7/2018 12:18:24 AM ******/
DROP DATABASE [CollegeStudents]
GO

/****** Object:  Database [CollegeStudents]    Script Date: 6/7/2018 12:18:24 AM ******/
CREATE DATABASE [CollegeStudents]  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 2 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [CollegeStudents] SET COMPATIBILITY_LEVEL = 140
GO

ALTER DATABASE [CollegeStudents] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [CollegeStudents] SET ANSI_NULLS OFF
GO

ALTER DATABASE [CollegeStudents] SET ANSI_PADDING OFF
GO

ALTER DATABASE [CollegeStudents] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [CollegeStudents] SET ARITHABORT OFF
GO

ALTER DATABASE [CollegeStudents] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [CollegeStudents] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [CollegeStudents] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [CollegeStudents] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [CollegeStudents] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [CollegeStudents] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [CollegeStudents] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [CollegeStudents] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [CollegeStudents] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [CollegeStudents] SET ALLOW_SNAPSHOT_ISOLATION ON
GO

ALTER DATABASE [CollegeStudents] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [CollegeStudents] SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE [CollegeStudents] SET  MULTI_USER
GO

ALTER DATABASE [CollegeStudents] SET ENCRYPTION ON
GO

ALTER DATABASE [CollegeStudents] SET QUERY_STORE = ON
GO

ALTER DATABASE [CollegeStudents] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO


ALTER DATABASE [CollegeStudents] SET  READ_WRITE
GO


