insert into majors(major_number, major_title) values (1100,'GENERAL AGRICULTURE')
insert into majors(major_number, major_title) values (1101,'AGRICULTURE PRODUCTION AND MANAGEMENT')
insert into majors(major_number, major_title) values (1102,'AGRICULTURAL ECONOMICS')
insert into majors(major_number, major_title) values (1103,'ANIMAL SCIENCES')
insert into majors(major_number, major_title) values (1104,'FOOD SCIENCE')
insert into majors(major_number, major_title) values (1105,'PLANT SCIENCE AND AGRONOMY')
insert into majors(major_number, major_title) values (1106,'SOIL SCIENCE')
insert into majors(major_number, major_title) values (1199,'MISCELLANEOUS AGRICULTURE')
insert into majors(major_number, major_title) values (1302,'FORESTRY')
insert into majors(major_number, major_title) values (1303,'NATURAL RESOURCES MANAGEMENT')
insert into majors(major_number, major_title) values (6000,'FINE ARTS')
insert into majors(major_number, major_title) values (6001,'DRAMA AND THEATER ARTS')
insert into majors(major_number, major_title) values (6002,'MUSIC')
insert into majors(major_number, major_title) values (6003,'VISUAL AND PERFORMING ARTS')
insert into majors(major_number, major_title) values (6004,'COMMERCIAL ART AND GRAPHIC DESIGN')
insert into majors(major_number, major_title) values (6005,'FILM VIDEO AND PHOTOGRAPHIC ARTS')
insert into majors(major_number, major_title) values (6007,'STUDIO ARTS')
insert into majors(major_number, major_title) values (6099,'MISCELLANEOUS FINE ARTS')
insert into majors(major_number, major_title) values (1301,'ENVIRONMENTAL SCIENCE')
insert into majors(major_number, major_title) values (3600,'BIOLOGY')
insert into majors(major_number, major_title) values (3601,'BIOCHEMICAL SCIENCES')
insert into majors(major_number, major_title) values (3602,'BOTANY')
insert into majors(major_number, major_title) values (3603,'MOLECULAR BIOLOGY')
insert into majors(major_number, major_title) values (3604,'ECOLOGY')
insert into majors(major_number, major_title) values (3605,'GENETICS')
insert into majors(major_number, major_title) values (3606,'MICROBIOLOGY')
insert into majors(major_number, major_title) values (3607,'PHARMACOLOGY')
insert into majors(major_number, major_title) values (3608,'PHYSIOLOGY')
insert into majors(major_number, major_title) values (3609,'ZOOLOGY')
insert into majors(major_number, major_title) values (3611,'NEUROSCIENCE')
insert into majors(major_number, major_title) values (3699,'MISCELLANEOUS BIOLOGY')
insert into majors(major_number, major_title) values (4006,'COGNITIVE SCIENCE AND BIOPSYCHOLOGY')
insert into majors(major_number, major_title) values (6200,'GENERAL BUSINESS')
insert into majors(major_number, major_title) values (6201,'ACCOUNTING')
insert into majors(major_number, major_title) values (6202,'ACTUARIAL SCIENCE')
insert into majors(major_number, major_title) values (6203,'BUSINESS MANAGEMENT AND ADMINISTRATION')
insert into majors(major_number, major_title) values (6204,'OPERATIONS LOGISTICS AND E-COMMERCE')
insert into majors(major_number, major_title) values (6205,'BUSINESS ECONOMICS')
insert into majors(major_number, major_title) values (6206,'MARKETING AND MARKETING RESEARCH')
insert into majors(major_number, major_title) values (6207,'FINANCE')
insert into majors(major_number, major_title) values (6209,'HUMAN RESOURCES AND PERSONNEL MANAGEMENT')
insert into majors(major_number, major_title) values (6210,'INTERNATIONAL BUSINESS')
insert into majors(major_number, major_title) values (6211,'HOSPITALITY MANAGEMENT')
insert into majors(major_number, major_title) values (6212,'MANAGEMENT INFORMATION SYSTEMS AND STATISTICS')
insert into majors(major_number, major_title) values (6299,'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION')
insert into majors(major_number, major_title) values (1901,'COMMUNICATIONS')
insert into majors(major_number, major_title) values (1902,'JOURNALISM')
insert into majors(major_number, major_title) values (1903,'MASS MEDIA')
insert into majors(major_number, major_title) values (1904,'ADVERTISING AND PUBLIC RELATIONS')
insert into majors(major_number, major_title) values (2001,'COMMUNICATION TECHNOLOGIES')
insert into majors(major_number, major_title) values (2100,'COMPUTER AND INFORMATION SYSTEMS')
insert into majors(major_number, major_title) values (2101,'COMPUTER PROGRAMMING AND DATA PROCESSING')
insert into majors(major_number, major_title) values (2102,'COMPUTER SCIENCE')
insert into majors(major_number, major_title) values (2105,'INFORMATION SCIENCES')
insert into majors(major_number, major_title) values (2106,'COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY')
insert into majors(major_number, major_title) values (2107,'COMPUTER NETWORKING AND TELECOMMUNICATIONS')
insert into majors(major_number, major_title) values (3700,'MATHEMATICS')
insert into majors(major_number, major_title) values (3701,'APPLIED MATHEMATICS')
insert into majors(major_number, major_title) values (3702,'STATISTICS AND DECISION SCIENCE')
insert into majors(major_number, major_title) values (4005,'MATHEMATICS AND COMPUTER SCIENCE')
insert into majors(major_number, major_title) values (2300,'GENERAL EDUCATION')
insert into majors(major_number, major_title) values (2301,'EDUCATIONAL ADMINISTRATION AND SUPERVISION')
insert into majors(major_number, major_title) values (2303,'SCHOOL STUDENT COUNSELING')
insert into majors(major_number, major_title) values (2304,'ELEMENTARY EDUCATION')
insert into majors(major_number, major_title) values (2305,'MATHEMATICS TEACHER EDUCATION')
insert into majors(major_number, major_title) values (2306,'PHYSICAL AND HEALTH EDUCATION TEACHING')
insert into majors(major_number, major_title) values (2307,'EARLY CHILDHOOD EDUCATION')
insert into majors(major_number, major_title) values (2308,'SCIENCE AND COMPUTER TEACHER EDUCATION')
insert into majors(major_number, major_title) values (2309,'SECONDARY TEACHER EDUCATION')
insert into majors(major_number, major_title) values (2310,'SPECIAL NEEDS EDUCATION')
insert into majors(major_number, major_title) values (2311,'SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION')
insert into majors(major_number, major_title) values (2312,'TEACHER EDUCATION: MULTIPLE LEVELS')
insert into majors(major_number, major_title) values (2313,'LANGUAGE AND DRAMA EDUCATION')
insert into majors(major_number, major_title) values (2314,'ART AND MUSIC EDUCATION')
insert into majors(major_number, major_title) values (2399,'MISCELLANEOUS EDUCATION')
insert into majors(major_number, major_title) values (3501,'LIBRARY SCIENCE')
insert into majors(major_number, major_title) values (1401,'ARCHITECTURE')
insert into majors(major_number, major_title) values (2400,'GENERAL ENGINEERING')
insert into majors(major_number, major_title) values (2401,'AEROSPACE ENGINEERING')
insert into majors(major_number, major_title) values (2402,'BIOLOGICAL ENGINEERING')
insert into majors(major_number, major_title) values (2403,'ARCHITECTURAL ENGINEERING')
insert into majors(major_number, major_title) values (2404,'BIOMEDICAL ENGINEERING')
insert into majors(major_number, major_title) values (2405,'CHEMICAL ENGINEERING')
insert into majors(major_number, major_title) values (2406,'CIVIL ENGINEERING')
insert into majors(major_number, major_title) values (2407,'COMPUTER ENGINEERING')
insert into majors(major_number, major_title) values (2408,'ELECTRICAL ENGINEERING')
insert into majors(major_number, major_title) values (2409,'ENGINEERING MECHANICS PHYSICS AND SCIENCE')
insert into majors(major_number, major_title) values (2410,'ENVIRONMENTAL ENGINEERING')
insert into majors(major_number, major_title) values (2411,'GEOLOGICAL AND GEOPHYSICAL ENGINEERING')
insert into majors(major_number, major_title) values (2412,'INDUSTRIAL AND MANUFACTURING ENGINEERING')
insert into majors(major_number, major_title) values (2413,'MATERIALS ENGINEERING AND MATERIALS SCIENCE')
insert into majors(major_number, major_title) values (2414,'MECHANICAL ENGINEERING')
insert into majors(major_number, major_title) values (2415,'METALLURGICAL ENGINEERING')
insert into majors(major_number, major_title) values (2416,'MINING AND MINERAL ENGINEERING')
insert into majors(major_number, major_title) values (2417,'NAVAL ARCHITECTURE AND MARINE ENGINEERING')
insert into majors(major_number, major_title) values (2418,'NUCLEAR ENGINEERING')
insert into majors(major_number, major_title) values (2419,'PETROLEUM ENGINEERING')
insert into majors(major_number, major_title) values (2499,'MISCELLANEOUS ENGINEERING')
insert into majors(major_number, major_title) values (2500,'ENGINEERING TECHNOLOGIES')
insert into majors(major_number, major_title) values (2501,'ENGINEERING AND INDUSTRIAL MANAGEMENT')
insert into majors(major_number, major_title) values (2502,'ELECTRICAL ENGINEERING TECHNOLOGY')
insert into majors(major_number, major_title) values (2503,'INDUSTRIAL PRODUCTION TECHNOLOGIES')
insert into majors(major_number, major_title) values (2504,'MECHANICAL ENGINEERING RELATED TECHNOLOGIES')
insert into majors(major_number, major_title) values (2599,'MISCELLANEOUS ENGINEERING TECHNOLOGIES')
insert into majors(major_number, major_title) values (5008,'MATERIALS SCIENCE')
insert into majors(major_number, major_title) values (4002,'NUTRITION SCIENCES')
insert into majors(major_number, major_title) values (6100,'GENERAL MEDICAL AND HEALTH SERVICES')
insert into majors(major_number, major_title) values (6102,'COMMUNICATION DISORDERS SCIENCES AND SERVICES')
insert into majors(major_number, major_title) values (6103,'HEALTH AND MEDICAL ADMINISTRATIVE SERVICES')
insert into majors(major_number, major_title) values (6104,'MEDICAL ASSISTING SERVICES')
insert into majors(major_number, major_title) values (6105,'MEDICAL TECHNOLOGIES TECHNICIANS')
insert into majors(major_number, major_title) values (6106,'HEALTH AND MEDICAL PREPARATORY PROGRAMS')
insert into majors(major_number, major_title) values (6107,'NURSING')
insert into majors(major_number, major_title) values (6108,'PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION')
insert into majors(major_number, major_title) values (6109,'TREATMENT THERAPY PROFESSIONS')
insert into majors(major_number, major_title) values (6110,'COMMUNITY AND PUBLIC HEALTH')
insert into majors(major_number, major_title) values (6199,'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS')
insert into majors(major_number, major_title) values (1501,'AREA ETHNIC AND CIVILIZATION STUDIES')
insert into majors(major_number, major_title) values (2601,'LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE')
insert into majors(major_number, major_title) values (2602,'FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES')
insert into majors(major_number, major_title) values (2603,'OTHER FOREIGN LANGUAGES')
insert into majors(major_number, major_title) values (3301,'ENGLISH LANGUAGE AND LITERATURE')
insert into majors(major_number, major_title) values (3302,'COMPOSITION AND RHETORIC')
insert into majors(major_number, major_title) values (3401,'LIBERAL ARTS')
insert into majors(major_number, major_title) values (3402,'HUMANITIES')
insert into majors(major_number, major_title) values (4001,'INTERCULTURAL AND INTERNATIONAL STUDIES')
insert into majors(major_number, major_title) values (4801,'PHILOSOPHY AND RELIGIOUS STUDIES')
insert into majors(major_number, major_title) values (4901,'THEOLOGY AND RELIGIOUS VOCATIONS')
insert into majors(major_number, major_title) values (5502,'ANTHROPOLOGY AND ARCHEOLOGY')
insert into majors(major_number, major_title) values (6006,'ART HISTORY AND CRITICISM')
insert into majors(major_number, major_title) values (6402,'HISTORY')
insert into majors(major_number, major_title) values (6403,'UNITED STATES HISTORY')
insert into majors(major_number, major_title) values (2201,'COSMETOLOGY SERVICES AND CULINARY ARTS')
insert into majors(major_number, major_title) values (2901,'FAMILY AND CONSUMER SCIENCES')
insert into majors(major_number, major_title) values (3801,'MILITARY TECHNOLOGIES')
insert into majors(major_number, major_title) values (4101,'PHYSICAL FITNESS PARKS RECREATION AND LEISURE')
insert into majors(major_number, major_title) values (5601,'CONSTRUCTION SERVICES')
insert into majors(major_number, major_title) values (5701,'ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION')
insert into majors(major_number, major_title) values (5901,'TRANSPORTATION SCIENCES AND TECHNOLOGIES')
insert into majors(major_number, major_title) values (4000,'MULTI/INTERDISCIPLINARY STUDIES')
insert into majors(major_number, major_title) values (3201,'COURT REPORTING')
insert into majors(major_number, major_title) values (3202,'PRE-LAW AND LEGAL STUDIES')
insert into majors(major_number, major_title) values (5301,'CRIMINAL JUSTICE AND FIRE PROTECTION')
insert into majors(major_number, major_title) values (5401,'PUBLIC ADMINISTRATION')
insert into majors(major_number, major_title) values (5402,'PUBLIC POLICY')
insert into majors(major_number, major_title) values (bbbb ,'N/A (less than bachelor''s degree)')
insert into majors(major_number, major_title) values (5000,'PHYSICAL SCIENCES')
insert into majors(major_number, major_title) values (5001,'ASTRONOMY AND ASTROPHYSICS')
insert into majors(major_number, major_title) values (5002,'ATMOSPHERIC SCIENCES AND METEOROLOGY')
insert into majors(major_number, major_title) values (5003,'CHEMISTRY')
insert into majors(major_number, major_title) values (5004,'GEOLOGY AND EARTH SCIENCE')
insert into majors(major_number, major_title) values (5005,'GEOSCIENCES')
insert into majors(major_number, major_title) values (5006,'OCEANOGRAPHY')
insert into majors(major_number, major_title) values (5007,'PHYSICS')
insert into majors(major_number, major_title) values (5098,'MULTI-DISCIPLINARY OR GENERAL SCIENCE')
insert into majors(major_number, major_title) values (5102,'NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL TECHNOLOGIES')
insert into majors(major_number, major_title) values (5200,'PSYCHOLOGY')
insert into majors(major_number, major_title) values (5201,'EDUCATIONAL PSYCHOLOGY')
insert into majors(major_number, major_title) values (5202,'CLINICAL PSYCHOLOGY')
insert into majors(major_number, major_title) values (5203,'COUNSELING PSYCHOLOGY')
insert into majors(major_number, major_title) values (5205,'INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY')
insert into majors(major_number, major_title) values (5206,'SOCIAL PSYCHOLOGY')
insert into majors(major_number, major_title) values (5299,'MISCELLANEOUS PSYCHOLOGY')
insert into majors(major_number, major_title) values (5403,'HUMAN SERVICES AND COMMUNITY ORGANIZATION')
insert into majors(major_number, major_title) values (5404,'SOCIAL WORK')
insert into majors(major_number, major_title) values (4007,'INTERDISCIPLINARY SOCIAL SCIENCES')
insert into majors(major_number, major_title) values (5500,'GENERAL SOCIAL SCIENCES')
insert into majors(major_number, major_title) values (5501,'ECONOMICS')
insert into majors(major_number, major_title) values (5503,'CRIMINOLOGY')
insert into majors(major_number, major_title) values (5504,'GEOGRAPHY')
insert into majors(major_number, major_title) values (5505,'INTERNATIONAL RELATIONS')
insert into majors(major_number, major_title) values (5506,'POLITICAL SCIENCE AND GOVERNMENT')
insert into majors(major_number, major_title) values (5507,'SOCIOLOGY')
insert into majors(major_number, major_title) values (5599,'MISCELLANEOUS SOCIAL SCIENCES')